### ISSUE TITLE
Cant type letters in the search bar

### ISSUE THREAD

**Issue by Sasa76** [deep-gaurav/MusicPiped#42] opened 2019-02-04 12:20 UTC
Cant type in a search bar unless you tap at the search bar one letter at a time which is frustrating. Example if i want to type 'music' i have to press M then another tap at the search bar then press u then another tap at the search bar then press s .. And so on 
Hair pulling moment indeed .. Luckily im bald lol

Huawei Mediapad Tablet, Android 6.0

**Comment by deep-gaurav** [comment] 2019-02-04 12:38
That's a strange issue, has it been that since first time you used or is it something that is new? And does it happen everytime or is it occassional?

Thanks for reporting

**Comment by Sasa76** [comment] 2019-02-04 12:48
A bit of history: confession: am a app hoarder
- Download music pipe from fdroid a few weeks ago
- Downloaded but never opened in fact forgot about it until couple of days ago when fdroid notified of a new update
- Downloaded the update but didnt open it
- open the app today for the first time thats when the issue crop up.
- Will try the app again shortly after this
- Am using  REBIT-A keyboard app

**Comment by deep-gaurav** [comment] 2019-02-04 12:51
Thanks for info,
Can you also tell what actually happens when you type, does keyboard goes down and text field loses focus or keyboard remains open and just textfield loses focus.

**Comment by Sasa76** [comment] 2019-02-04 13:35
A bit of history: confession: am a app hoarder
- Download music pipe from fdroid a few weeks ago
- Downloaded but never opened in fact forgot about it until couple of days ago when fdroid notified of a new update
- Downloaded the update but didnt open it
- open the app today for the first time thats when the issue crop up.
- Will try the app again shortly after this
- Am using  REBIT-A keyboard app

**Comment by Sasa76** [comment] 2019-02-04 13:50
Hi tried several time still cant .. The cursor remains active .. Hard to describe so i made a video. Hope this will explains it

https://drive.google.com/file/d/1idajSEYudbmSsI6g_V4FvrMpZgiQqNQc/view?usp=drivesdk

**Comment by deep-gaurav** [comment] 2019-02-04 18:21
I can view the video and both text field and keyboard remains active. Still presses aren't registering.. I can not really try anything for a day due to college work,. But till then can you try changing keyboard to aosp or Google keyboard. Just to confirm if it's keyboard related bug or not. Although I tried using same keyboard on my device but can't reproduce issue.
Thanks

**Comment by Sasa76** [comment] 2019-02-05 06:12
I change to Gboard and it works!!! It seems that the app wont work if i use REBIT A keyboard. When i change to google's kboard it works instantly. Keyboard bug lies on whose end, yours or rebit?

Thanks for the prompt response :)

**Comment by deep-gaurav** [comment] 2019-02-05 18:18
I'm not sure, but this could either be a Keyboard fault or Flutter issue., I'm closing issue to keep issues clean. Will raise an issue in flutter repo after some testing

**Closed by deep-gaurav** 2019-02-05 18:18 UTC
