### ISSUE TITLE
Add a download feature to the MusicPiped app 

### ISSUE THREAD

**Issue by chrisbarth01** [deep-gaurav/MusicPiped#80] opened 2019-05-04 17:08 UTC
#### Components
The component I want to suggest is a download button that will aid users (who wish) to download any music they want. 

---

#### Proposal Description
Though I understand that the MusicPiped app is a *music streaming app* but there are certain users like me who see certain songs and wish they had it downloaded on their device. I propose that an option to download any music should be added. This feature will be optional; only users who want to download a music will use it. This feature can be added as a download symbol on the downside of each and every music that appears on the search result.

---

#### Mockups / Examples
Below is a mock-up of my suggestion, it is an edited screenshot;
![PicsArt_05-04-03 08 20](https://user-images.githubusercontent.com/49325171/57181932-a3448200-6e91-11e9-9be0-3d1e7138f282.png)

---

#### Benefits
- If this feature is added, users will be able to also download any music which they want to. 

---

#### Conclusion 
This is quite important since the app streams its music from YouTube and it's obvious that there are many YouTube songs which users will definitely want downloaded on their device....

**Comment by ArmeF97** [comment] 2019-06-08 09:56
Duplicate of #23

**Comment by deep-gaurav** [comment] 2019-06-08 12:43
I'm closing this issue as duplicate

**Closed by deep-gaurav** 2019-06-08 12:43 UTC
