### ISSUE TITLE
Latest version fails to build in F-Droid 

### ISSUE THREAD

**Issue by esmoak** [deep-gaurav/MusicPiped#104] opened 2019-07-28 16:57 UTC
See: 
https://f-droid.org/wiki/page/deep.ryd.rydplayer/lastbuild

Discovered from this thread:
https://gitlab.com/fdroid/rfp/issues/758

**Comment by deep-gaurav** [comment] 2019-07-28 19:41
Thanks for effort, from logs it send like dart version (and flutter) is not up to date while compiling

**Comment by deep-gaurav** [comment] 2019-08-29 16:29
I think it's solved now, closing

**Comment by licaon-kter** [comment] 2019-11-04 09:21
@deep-gaurav Any idea why it takes more than 7200 seconds (the default timeout) for it to build? Is this normal: Ref: https://f-droid.org/wiki/page/deep.ryd.rydplayer/lastbuild_59

**Comment by deep-gaurav** [comment] 2019-11-04 10:21
It seems to be stuck at some prebuild task.
I'm not aware of any prebuild task. There could be some flutter generated tasks.

I'm not familiar with Gradle enough. And can't understand what task fdroid builder is trying to execute.

Also flutter has updated since then, so it might be worth trying to update flutter version specified in metadata

**Comment by licaon-kter** [comment] 2019-11-04 10:47
@deep-gaurav To which version?

**Comment by deep-gaurav** [comment] 2019-11-04 11:52
Oh I get it,
It's not about flutter,
Requirement is flutter version required is 1.5 right now and metadata specified 1.8

Prebuild probably means
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata%2Fdeep.ryd.rydplayer.yml#L241

And flutter get might be the cause of fail.
A dependency (fluttery_seekbar) used no longer exists in pub. 
flutter get must be failing due to it.
I'll fix, and push an update today

**Comment by deep-gaurav** [comment] 2019-11-12 05:41
@licon-kter published a new release with many fixes and removed dependency on that package, it should build now. I've tested it with latest stable `flutter 1.9.1+hotfix.6`

**Comment by licaon-kter** [comment] 2019-11-12 10:13
https://gitlab.com/fdroid/fdroiddata/commit/0e8cb1a2ab3c9c198968cf4657ea345bddb582ef

**Comment by deep-gaurav** [comment] 2019-11-15 00:25
Latest build succeeded, so closing this issue

**Closed by deep-gaurav** 2019-11-15 00:25 UTC
