### ISSUE TITLE
Stops if I leave the app

### ISSUE THREAD

**Issue by Sughosha** [deep-gaurav/MusicPiped#120] opened 2020-01-12 03:26 UTC
The app stops playback if I press the back ("<") button on my phone i.e. I does not play in background.

**Comment by deep-gaurav** [comment] 2020-01-12 03:29
It's by design, if main activity stops, app will stop, you can use your home screen button to exit app and Still have it play in background. Removing from recent will stop app

**Comment by deep-gaurav** [comment] 2020-01-12 03:29
I'm closing this issue since it's currently by design

**Closed by deep-gaurav** 2020-01-12 03:29 UTC
