### ISSUE TITLE
Error when selecting search result

### ISSUE THREAD

**Issue by Sarkasper** [deep-gaurav/MusicPiped#18] opened 2018-11-02 04:01 UTC
Cannot play given url ERROR 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at deep.ryd.rydplayer.testPipe.doInBackground(MainActivity.java:1096)
	at deep.ryd.rydplayer.testPipe.doInBackground(MainActivity.java:1068)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by Sarkasper** [comment] 2018-11-02 17:21
It only happens with one upload* (out of the three I tried), it's also persistent after clearing data.

* https://www.youtube.com/watch?v=IaknxWDWeLw

**Comment by deep-gaurav** [comment] 2018-11-03 03:43
Ok I got the error, the problem is that YouTube is not providing any audio stream for that video, just video streams, this is rare, and cannot be fixed from my side

**Comment by deep-gaurav** [comment] 2018-11-03 03:44
You can try opening it in newpipe and the download button will not show audio downloads bcz it doesn't have any audio streams,

**Comment by deep-gaurav** [comment] 2019-04-28 14:22
I think it's fixed in new versions closing issue

**Closed by deep-gaurav** 2019-04-28 14:22 UTC
