### ISSUE TITLE
[question] Backgroud playback

### ISSUE THREAD

**Issue by dimqua** [deep-gaurav/MusicPiped#113] opened 2019-11-15 11:12 UTC
When I remove the app from "recents", the notification disappears, and the playback is stopped. In other words, when I close MusicPiped, songs do not play in the background. Is there any solution for this problem? I'm using LOS 17.

NewPipe works in such situation, for example.

**Comment by deep-gaurav** [comment] 2019-11-15 11:50
No, this is by design, Transferring data back and forth between service and flutter app and service was heavy load for many devices and was causing many crashes.

So since v2.0 service doesn't have it's queue or playback and so if app is removed, it is stopped

**Comment by deep-gaurav** [comment] 2019-11-15 11:51
I'm closing this issue since this is design right now.
If someone is interested in syncing service and app with their separate queue for background playback without app open, I'll accept pull requests. But do not have enough time to make it or maintain it

**Closed by deep-gaurav** 2019-11-15 11:51 UTC
