### ISSUE TITLE
Several Bugs

### ISSUE THREAD

**Issue by anotherboringuser** [deep-gaurav/MusicPiped#93] opened 2019-05-25 08:12 UTC
Hi, 
I have several issues in the new MusicPiped Version. I've tried uninstalling and reinstalling the app but it didn't help. 
1. Adding tracks to Favorite doesn't work. It does say "Added to Favorite" at the bottom of the screen, but the tracks don't show up in Favorite. 
2. Adding tracks to Playlists doesn't work. The slide menue is closed after tapping on "Add to", but I can't select a Playlist and tracks don't end up in one. 
3. In dark mode, sometimes there are some symbols missing in the dot in the Playlists tab. 
![Screenshot_2019-05-25-09-35-45_1](https://user-images.githubusercontent.com/44035735/58366627-72c29780-7ed5-11e9-8203-51d16ee62a71.png)

Are those bugs or am I doing something wrong? 

The App was installed using F-Droid. I'm using Version 1.2.0 on Android 8.0.0

**Comment by deep-gaurav** [comment] 2019-05-25 08:27
No you're not doing anything wrong, the app is bug infested. 

1 and 2 are regressions introduced in 1.2.0 and doesnt exist in earlier versions.
I was busy till yesterday due to exams so could not notice.

The app is actually pretty messy in architecture mostly due to having to deal with dart to java communication bridge. This is reason for most bugs too.

I would like to take opportunity and announce new (and possibly better project), I'm working on a completely dart version with flutter web, it does not have to deal with the language bridges so will not have most bugs afaik. 

Moreover since it's a web version you can even use on Desktop.
Here's link (Recommend chrome) 

https://deep-gaurav.github.io

It is currently missing a lot of features like playlists.
But it should get feature complete soon without major bugs soon (a week or two).
It'll also be open source btw.

That all being said I'm not dropping this app completely but I want to have a completely working web version to redirect people to first then fix this app.

**Comment by deep-gaurav** [comment] 2019-06-07 20:03
Hi, I think mentioned bugs are fixed in v2.0.1. Closing issue

**Closed by deep-gaurav** 2019-06-07 20:03 UTC
